Vagrant.configure("2") do |config|
  
  config.vm.define "elastic-vm" do |elastic|
    elastic.vm.network "private_network", ip: "10.0.0.10"
    elastic.vm.hostname = "elastic-vm"
    elastic.vm.network "forwarded_port", guest: 9200, host: 9200, protocol: "tcp"  
    elastic.vm.provider :virtualbox do |v|
      v.name = "elastic-vm"
    end

    elastic.vm.box = "centos/7"
    elastic.vm.synced_folder "../", "/vagrant"
    elastic.vm.provision "shell", inline: "/bin/bash /vagrant/startup/provision/elasticsearch.sh"
    elastic.ssh.insert_key = false
  end

  config.vm.define "web-vm" do |web|
    web.vm.network "private_network", ip: "10.0.0.20"
    web.vm.hostname = "web-vm"
    web.vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp"  
    web.vm.provider :virtualbox do |v|
      v.name = "web"
    end
    web.vm.box = "centos/7"
    web.vm.synced_folder "../", "/vagrant"
    web.vm.provision "shell", inline: "/bin/bash /vagrant/startup/provision/web.sh"
    web.ssh.insert_key = false
  end

end

